# Sample Template

[awm-layouts]
"􁕥" = "floating.png"
"􁕣" = "tile.png"
"􁇢" = "tileleft.png"
"􀧱" = "tilebottom.png"
"􁹮" = "tiletop.png"
"􁽩" = "fair.png"
"􁀃" = "fairv.png"
"􁀇" = "fairh.png"
"􁀋" = "cornersw.png"
"􁀸" = "max.png"
