#!/bin/bash
# shellcheck disable=SC2181

set -o noclobber
set -o errexit
set -o pipefail
set -o errtrace
set -E -o functrace

declare TIME; TIME="$(date '+%s%3N')"
declare BASE; BASE=$(dirname "$(realpath "$0")")
declare XCNF="$HOME/.config/xico/config.toml"
declare SYNOPSIS='xico [-t path] | [-u] | [-c char path]'
declare -A CFG=( [geo]=500 [ext]=png [mod]=show.hlp [tpl]="$XCNF" )
declare SVG="${BASE}/xico.svg"
declare SED="${BASE}/xico.sed"

function get.took { bc <<< "scale=2; $(( $(date '+%s%3N') - TIME ))/1000"; }
function show.age { printf '\n\e[32mtook %ss\n' "$(get.took)"; }
function show.hlp { printf '\n\e[34m  %s\n\n\n' "$SYNOPSIS"; }
function show.err { printf '\n\e[31m %s\e[0m\n' "$*"; }
function do.clean { (( $? )) && show.hlp; show.age; }
function do.fatal { show.err "$*"; exit 1; }

function fromchr {
  local c="${1:-${CFG[chr]:?$(show.err NO_CHAR)}}"
  local o="${2:-${CFG[out]:?$(show.err NO_PATH)}}"

  local s="${CFG[geo]}"
  local b="${o%/*}"
  local t="/tmp/xico/${RANDOM}.svg"

  [ "$o" != "$b" ] && ! [ -d "$b" ] && mkdir "$b" 2>/dev/null

  (( XICO_DEBUG )) && printf '%s:%s:->:%s___%s\n' "$t" "$c" "$o" "$b"

  sed -e "s/__XICO__/${c}/" "$SVG" > "$t"

  inkscape -w "$s" -h "$s" "$t" --export-type "${CFG[ext]}" -o "$o"
}

function fromtpl {
  local b
  [ -e "${CFG[tpl]}" ] || do.fatal TPL_NOT_FOUND
  while read -r L; do
    k="${L%% *}"; v="${L##* }"

    [ "$k" == 'base' ] && b="${v}" && continue

    fromchr "$k" "${b}/${v}"
  done < <(sed -E -f "$SED" < "${CFG[tpl]}")
}

# -------------------- #

trap do.clean EXIT

{ [ -e "$SVG" ] && [ -e "$SED" ]; } || do.fatal MISSING_INTERNALS

  [ -d "/tmp/xico" ] || mkdir "$b" 2>/dev/null || true

# -------------------- #

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do case $1 in
  -c|--char)     CFG[mod]=fromchr; shift; CFG[chr]="$1" ;;
  -t|--template) CFG[mod]=fromtpl; shift; CFG[tpl]="$1" ;;
  -u|--user)     CFG[mod]=fromtpl; shift;               ;;
  -s|--size)     CFG[geo]="$2";    shift;               ;;
  -h|--help)     show.hlp                               ;;
  *)             show.hlp; do.fatal BAD_ARG             ;;
esac; shift; done

CFG[out]="${*}"

(( XICO_DEBUG )) && declare -p CFG

${CFG[mod]}
